### ISSUE TITLE
No comment and no error

### ISSUE THREAD

**Issue by jayvdb** [jo-sm/at-dependabot-merge#5]
I tested this github action at https://github.com/jayvdb/jekyll-netlify/pull/8, where https://github.com/jayvdb/jekyll-netlify/pull/8#issuecomment-878214635 was correctly added automatically.

I duplicated this at https://github.com/swift-nav/libsettings/pull/331 , and then did a rebase to https://github.com/swift-nav/libsettings/pull/330 . 

https://github.com/swift-nav/libsettings/actions/runs/1024750249 ran, however there is no comment, and no error.

My guess is that the "CI" workflow finished, triggering the workflow for this github action, but the "Python" workflow had not finished, and the action silently bailed out at https://github.com/jo-sm/at-dependabot-merge/blob/c72dbd4/src/action.js#L44

**Comment by jo-sm** [comment]
Hey @jayvdb, sorry for the trouble with this. As far as I understand GitHub Actions, due to the way I've written this action unless you can guarantee the order of the workflow runs (meaning, CI is always after Python or others) there isn't really a way to handle this without running the action against all workflows. You should be able to accomplish this by [removing this line in your workflow](https://github.com/swift-nav/libsettings/blob/master/.github/workflows/auto-pr.yml#L5). 

The reason this happens is that the action waits for all workflows to either return ✅ or return that they're being skipped, so if some of the workflows were running when CI finished successfully the action wouldn't have added the comment. I did this to be safe based on my use cases, but maybe this is undesirable - what do you think?

FYI I changed the functionality yesterday to ignore skipped workflow runs and subsequently fixed an issue with that change (which is caused by a strange Dependabot workflow issue), so when you get a chance I'd recommend upgrading to version `v1.2`.

**Comment by jayvdb** [comment]
What about adding a flag, default disabled, to allow this action to proceed if the suite isnt finished?
It should then add the `merge` comment, and my guess is dependabot will do the merge.
If I know that the dependabot change can only break one workflow, I dont mind if the others dont finish before the merge,

**Comment by jo-sm** [comment]
Makes sense. I'll make an issue for it and should be able to add this flag in the next few days. For now if you want to use the action I'd recommend just commenting out that line in the workflow, which should solve the issue in the short term at the expense of having to run the action for each completed workflow, and once the option is added I'll reply to this issue.

**Comment by jo-sm** [comment]
Hi @jayvdb I just released a new version which adds `only-given-run` as an input, which should cover the case you're running into. Can you try it out?

**Comment by jayvdb** [comment]
It didnt work, and https://github.com/jo-sm/at-dependabot-merge/pull/11/files#r673685157 looks like the cause.

**Comment by jo-sm** [comment]
🤦 Sorry about that @jayvdb. I've released version `1.3.1` which correctly names the input to `only-given-run` and fixes a related bug to this input. Can you update and try it out?

**Comment by jayvdb** [comment]
It is working now.  Thanks.

**Comment by jo-sm** [comment]
@jayvdb Perfect! Also, can you let me know that the merging works even with pending workflows? I assume it should work but it's not clear from the docs if Dependabot also waits until pending workflows are finished.

**Comment by jayvdb** [comment]
When the merge command is used before all workflows are done, Dependabot waits until pending workflows are finished, and then merges.
